### ISSUE TITLE
点击打赏, 页面无反应

### ISSUE THREAD

**Issue by feynman-x** [YoubetDao/youbet-task#52]
点击 打赏按钮 时, 页面无反应, 打开控制台看到报错, 信息如下:

**错误日志:**
```
index-f8210f8f.js:315 Uncaught (in promise) Error: could not coalesce error (error={ "code": -32602, "message": "Expected null or object 'nativeCurrency'. Received:\nundefined" }, payload={ "id": 2, "jsonrpc": "2.0", "method": "wallet_addEthereumChain", "params": [ { "chainId": "0xa045c", "chainName": "OpenCampus-Testnet", "rpcUrls": [ "https://open-campus-codex-sepolia.drpc.org" ] } ] }, code=UNKNOWN_ERROR, version=6.13.1)
    at Ar (index-f8210f8f.js:315:17605)
    at KEe.getRpcError (index-f8210f8f.js:316:186221)
    at KEe.getRpcError (index-f8210f8f.js:316:191085)
    at index-f8210f8f.js:316:188326
```

钱包地址:
0xD904bbE4bd9900795b08bB62F62016cA11473593

chain: EDU chain

**Comment by wfnuser** [comment]
Good Catch. Let me check it out.

**Comment by wfnuser** [comment]
I would like to claim this issue.

**Comment by wfnuser** [comment]
I would like to claim this issue.

**Comment by wfnuser** [comment]
I would like to claim this issue.

**Comment by HangeZoe1** [comment]
issue was claim

**Comment by Dblaise181** [comment]
how to claim

**Comment by Mieondev** [comment]
Hi , how to claim?

**Comment by wfnuser** [comment]
> how to claim

Haha! If you’re interested, I can assign this to you. @Dblaise181, could you please share your Telegram contact so we can reach out to you? We’re currently in our beta phase.

@Mieondev @HangeZoe1, perhaps next time?

Let me know if you need any adjustments!

**Comment by wfnuser** [comment]
I would like to claim this issue.

**Comment by wfnuser** [comment]
I would like to claim this issue.

**Comment by wfnuser** [comment]
I would like to claim this issue.

**Comment by wfnuser** [comment]
I would like to claim this issue.
